"""
core/skill_registry.py
========================
Jarvis Skill / Module / Doc Registry.

Har baar Jarvis start hota hai, yeh module poore project ko scan kar ke
ek "registry" bana deta hai — jisme:
  1. `actions/` aur `agent/` ke andar jitne bhi python modules hain
     (skills/tools), un sab ka naam + purpose + functions list.
  2. Project root mein jitni bhi .md files hain (Modules.md, Commands.md,
     Architecture.md, Roadmap.md, Bug.md, Ideas.md, Tasks.md, waghera),
     un sab ka naam + short summary.

Yeh scan 100% DYNAMIC hai — koi hardcoded list nahi. Matlab jis din bhi
`actions/` mein koi nayi skill file dalo ya root mein koi nayi .md file
banao, agli baar Jarvis start hone par woh AUTOMATICALLY is registry
mein register ho jayegi. Manual editing ki zaroorat nahi.

Registry do jagah use hoti hai:
  - `SKILLS_REGISTRY.md`  -> human-readable file, disk par save hoti hai
                             (auto-generated, is file ko haath se edit
                             mat karo, har startup pe overwrite hoti hai).
  - `prompt_block()`      -> short summary jo system prompt ke saath
                             inject hoti hai, taake Jarvis KISI BHI request
                             ka jawab dene se pehle yeh dekh le ke koi
                             existing skill/module/doc already available
                             hai ya nahi.

Agar registry summary kaafi nahi hai to Jarvis `read_project_doc` tool
call kar ke kisi bhi .md file ko poora / detail mein padh sakta hai.
"""

import ast
from datetime import datetime
from pathlib import Path

from core.paths import BASE_DIR

REGISTRY_PATH = BASE_DIR / "SKILLS_REGISTRY.md"

# Jin folders ke andar python skill/action/module files scan karni hain.
# Naya folder add karna ho to bas yahan naam add kar dena.
MODULE_DIRS = ["actions", "agent"]

# Root-level .md docs jo auto-discover honge (koi hardcoded filename list nahi).
DOC_GLOB = "*.md"
IGNORE_DOCS = {"SKILLS_REGISTRY.md", "readme.md", "README.md"}


def _first_docstring(py_path: Path) -> str:
    try:
        tree = ast.parse(py_path.read_text(encoding="utf-8", errors="ignore"))
        doc = ast.get_docstring(tree)
        if doc:
            return doc.strip().splitlines()[0][:200]
    except Exception:
        pass
    return ""


def _top_level_defs(py_path: Path) -> list:
    try:
        tree = ast.parse(py_path.read_text(encoding="utf-8", errors="ignore"))
        return [
            n.name for n in tree.body
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and not n.name.startswith("_")
        ]
    except Exception:
        return []


def _has_tool_declarations(py_path: Path) -> bool:
    try:
        return "TOOL_DECLARATIONS" in py_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False


def scan_modules() -> list:
    """Actions/ aur agent/ ke andar har .py file ko scan karta hai."""
    modules = []
    for folder in MODULE_DIRS:
        d = BASE_DIR / folder
        if not d.exists():
            continue
        for py in sorted(d.glob("*.py")):
            if py.name.startswith("_"):
                continue
            modules.append({
                "module":    f"{folder}/{py.name}",
                "summary":   _first_docstring(py) or "(no docstring yet — is file mein docstring add karo taake routing behtar ho)",
                "functions": _top_level_defs(py),
                "has_tools": _has_tool_declarations(py),
            })
    return modules


def scan_docs() -> list:
    """Root ke andar har .md file ko scan karta hai."""
    docs = []
    for md in sorted(BASE_DIR.glob(DOC_GLOB)):
        if md.name in IGNORE_DOCS:
            continue
        try:
            text = md.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            text = ""
        summary = next((l.strip("# ").strip() for l in text.splitlines() if l.strip()), "")
        docs.append({"doc": md.name, "summary": summary[:200], "chars": len(text)})
    return docs


def build_registry() -> dict:
    """Poora scan chalata hai aur SKILLS_REGISTRY.md ko rewrite karta hai."""
    registry = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "modules": scan_modules(),
        "docs": scan_docs(),
    }
    try:
        _write_markdown(registry)
    except Exception as e:
        print(f"[Registry] ⚠️ Could not write {REGISTRY_PATH}: {e}")
    return registry


def _write_markdown(registry: dict) -> None:
    lines = [
        "<!-- AUTO-GENERATED by core/skill_registry.py — is file ko haath se edit mat karo. -->",
        "<!-- Har Jarvis startup par yeh dobara ban'ti hai. actions/ ya agent/ mein nayi -->",
        "<!-- .py file dalo, ya root mein nayi .md file banao — agli baar yahan khud register ho jayegi. -->",
        "",
        "# Jarvis Skill & Module Registry",
        f"_Last built: {registry['generated_at']}_",
        "",
        "## Action / Agent Modules",
        "",
    ]
    for m in registry["modules"]:
        tag = " *(TOOL_DECLARATIONS exposed)*" if m["has_tools"] else ""
        lines.append(f"- **{m['module']}**{tag} — {m['summary']}")
        if m["functions"]:
            lines.append(f"  - functions: {', '.join(m['functions'][:12])}")
    lines.append("")
    lines.append("## Project Docs (.md)")
    lines.append("")
    for d in registry["docs"]:
        lines.append(f"- **{d['doc']}** ({d['chars']} chars) — {d['summary']}")
    lines.append("")
    lines.append("## Jarvis is file ko kaise use kare")
    lines.append("")
    lines.append("1. Koi bhi naya kaam shuru karne se pehle yeh registry check karo (system prompt mein summary already maujood hai).")
    lines.append("2. Agar koi matching module ya doc already available hai, wahi use karo — dobara se wahi cheez mat banao.")
    lines.append("3. Agar kuch match nahi hota: pehle `read_project_doc` se related doc padho (agar lagta hai wahan info ho sakti hai).")
    lines.append("   Agar wahan bhi kuch nahi milta to naya module/skill banao, phir `save_memory` se ek note category=`projects` mein")
    lines.append("   save karo jisme yeh likha ho ke kya naya add hua — taake agli baar yeh registry rebuild ho to woh yahan bhi dikhe.")
    REGISTRY_PATH.write_text("\n".join(lines), encoding="utf-8")


def prompt_block(registry: dict, max_modules: int = 60) -> str:
    """System prompt mein inject karne wala compact summary."""
    mod_lines = [f"- {m['module']}: {m['summary']}" for m in registry["modules"][:max_modules]]
    doc_lines = [f"- {d['doc']}: {d['summary']}" for d in registry["docs"]]
    return (
        "\n\n=== SKILLS REGISTRY (auto-generated — poori detail SKILLS_REGISTRY.md mein hai) ===\n"
        "RULE: Kisi bhi request ka jawab dene / kaam karne se pehle pehle yahan dekho. Agar niche di gayi\n"
        "modules/docs list mein se koi related skill/module already maujood hai, WAHI use karo — dobara mat banao.\n"
        "Agar kuch bhi match nahi hota, to `read_project_doc` tool se related .md file poori padho, aur agar wahan\n"
        "bhi jawab na mile to naya module/skill/project banao aur `save_memory` (category: projects) se note save karo.\n\n"
        "Available modules:\n" + ("\n".join(mod_lines) if mod_lines else "(none found)") + "\n\n"
        "Available docs (read_project_doc se poora padh sakte ho):\n" + ("\n".join(doc_lines) if doc_lines else "(none found)")
    )


def read_doc(name: str, max_chars: int = 6000) -> str:
    """Kisi bhi root .md doc ko poora (ya truncate kar ke) padhta hai."""
    if not name:
        return "doc_name khali hai — koi filename batao (e.g. 'Modules.md')."
    path = BASE_DIR / name
    if not path.exists() or path.suffix.lower() != ".md":
        matches = [p for p in BASE_DIR.glob("*.md") if name.lower().replace(".md", "") in p.name.lower()]
        if not matches:
            return f"'{name}' naam ki koi .md file project root mein nahi mili."
        path = matches[0]
    text = path.read_text(encoding="utf-8", errors="ignore")
    if len(text) > max_chars:
        return text[:max_chars] + f"\n\n...[{path.name} truncated, {len(text) - max_chars} chars aur bache hain]"
    return text


if __name__ == "__main__":
    # Standalone run: `python core/skill_registry.py` -> registry rebuild + print
    reg = build_registry()
    print(f"[Registry] {len(reg['modules'])} modules, {len(reg['docs'])} docs -> {REGISTRY_PATH}")
